### PR TITLE
Feat: support same same currencies as checkout and fix currency display

### LINKED ISSUE #61: [request invoicing] Support ETH Native payments on all supported chains and REQ on Etheruem
# Problem

Only supports Ethereum, Polygon, and Sepolia.
Only supports a few stablecoins

# Solution

- [ ] Add ETH (native) payments on all supported chains
- [ ] Add REQ on Etheruem as part of the default list, but not the default selection.

### PR DESCRIPTION
**Pull request by aimensahnoun**
Resolves #61 #108 

This PR adds the following:

- Fixes the use of deprecated `currencyManager.from()` to use either `fromAddress()` or `getNativeCurrency()` depending on the use-case

- Enable the possibility to create and pay with native currencies by adding  `pn-eth-fee-proxy-contract`

- Adds all of the currencies that are supported by `Payment Widget` into the invoicing template to enable full interoperability

- Custom currencies are now appended to the default currency array instead of overriding them.

- Make sure that currencies are unique so we don't have duplicates in currency manager.

- Enable switching to the newly added chains.

It might be worth to add a `overrideDefaultCurrencies` boolean as a prop in the future to allow users to override the default currencies still.

### Screenshots:
CleanShot 2024-09-02 at 22 43 26

CleanShot 2024-09-02 at 22 43 42

CleanShot 2024-09-02 at 22 44 01

CleanShot 2024-09-02 at 22 44 16

CleanShot 2024-09-02 at 22 44 23

## Summary by CodeRabbit

- **New Features**
	- Enhanced currency handling for ERC20 tokens in invoice creation and dashboard components.
	- Introduced new utility function for streamlined currency retrieval based on type.
	- Added support for new stablecoin identifiers in the payment widget.
	- Expanded the range of supported currencies in the currency management system.

- **Bug Fixes**
	- Improved robustness in handling request data and approval checks based on currency type.

- **Documentation**
	- Updated comments and structure for better clarity and maintainability across components.

- **Chores**
	- Restructured import statements for better organization and readability throughout the codebase.

### CODE REVIEW

File: packages/invoice-dashboard/src/utils/getCurrency.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+  currency: Types.RequestLogic.ICurrency,
+  currencyManager: CurrencyManager
+) => {
+  const currencyResult =
+    currency.type === Types.RequestLogic.CURRENCY.ETH
+      ? currencyManager.getNativeCurrency(currency.type, currency.network!)
+      : currencyManager.fromAddress(currency.value, currency.network);
+
+  return currencyResult;
+};
```
[the remark this answers is not in the document]
Comment (aimensahnoun) [reply packages/invoice-dashboard/src/utils/getCurrency.ts:14]: We always have network in the currency.

File: packages/create-invoice-form/src/lib/utils/prepareRequest.ts [hunk 2]
```diff
@@ -18,105 +18,112 @@ export const prepareRequestParams = ({
...
+
+  return {
+    requestInfo: {
+      currency: {
+        type: currency.type,
+        value: isERC20 ? currency.address : "eth",
+        network: currency.network,
+      },
+      expectedAmount: parseUnits(
+        invoiceTotals.totalAmount.toFixed(2),
```
Comment (MantisClone) [inline packages/create-invoice-form/src/lib/utils/prepareRequest.ts:32]: We shouldn't be rounding with `toFixed(2)` when writing data from the user to the protocol. 

We should round only when displaying long numbers.

Let's create a new issue to fix this.

File: shared/utils/initCurrencyManager.ts [hunk 3]
```diff
@@ -9,22 +9,75 @@ const defaultCurrencyIds = [
...
+        if (currency.type === Types.RequestLogic.CURRENCY.ETH) {
+          return t.type === currency.type && t.network === currency.network;
+        } else if (currency.type === Types.RequestLogic.CURRENCY.ERC20) {
+          return (
+            t.network === currency.network &&
+            t.address?.toLowerCase() === currency.address?.toLowerCase()
+          );
+        }
+      })
+  );
```
Comment (MantisClone) [inline shared/utils/initCurrencyManager.ts:79]: Why does this work?  I find this logic confusing. Is there a way to refactor it to be more clear?

`index === self.findIndex()` seems redundant and unnecessary, even if it isn't.

Comment (aimensahnoun) [reply shared/utils/initCurrencyManager.ts:79]: Since now custom currencies are appended instead of overriding the default currencies there could be duplicates if we need to remove them.

The code itself checks on `network` and `address` in the case of ERC20 since those are the unique identifiers and for native currencies the main one is the `network` with the addition of `type`

`self.findIndex` would return to us the first element that meets the criteria,.

-  if it is the same index, we are comparing the same element which we should keep. 
- If it is not the same index it means we have a duplicate, and since the index of current element and the one found are not the same the equation returns false, removing the duplicate from the list.

@MantisClone

**Review by MantisClone — APPROVED** [review]

File: packages/create-invoice-form/src/lib/utils/prepareRequest.ts (hunk 2 above)
Comment (MantisClone) [reply packages/create-invoice-form/src/lib/utils/prepareRequest.ts:32]: https://github.com/RequestNetwork/web-components/issues/121
